template: |
  ## Changes

  $CHANGES

  $CONTRIBUTORS

name-template: 'v$NEXT_PATCH_VERSION'
tag-template: 'v$NEXT_PATCH_VERSION'

categories:
  - title: 'Features'
    labels:
      - 'feature'
      - 'enhancement'
      - 'feat'
  - title: 'Bug Fixes'
    labels:
      - 'bug'
      - 'fix'
  - title: 'Maintenance'
    labels:
      - 'chore'
      - 'maintenance'
      - 'refactor'
  - title: 'Documentation'
    labels:
      - 'docs'
      - 'documentation'
  - title: 'CI/CD'
    labels:
      - 'ci'
      - 'github-actions'
      - 'workflow'

change-template: '- $TITLE (#$NUMBER) @$AUTHOR'
no-changes-template: 'No user-facing changes in this release.'