# Generic Kubernetes Manifest for ACS SMTP Relay
#
# --- Instructions ---
#
# 1. Create the Namespace (if it doesn't exist already):
#    kubectl create namespace my-namespace
#
# 2. Create the Secret for the Azure Connection String:
#    Replace '...' with your actual connection string.
#
#    kubectl create secret generic acs-relay-secrets \
#      --from-literal=ACS_CONNECTION_STRING='endpoint=https://...;accesskey=...' \
#      -n my-namespace
#
# 3. Edit this file below:
#    - Replace <YOUR_CONTAINER_IMAGE_PATH> with the full path to the image in your registry.
#    - Replace <YOUR_SENDER_ADDRESS> with your verified "MailFrom" address from Azure.
#
# 4. Apply this Manifest to your Cluster:
#    kubectl apply -f k8s/acs-relay.yaml -n my-namespace
#
# ---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: acs-smtp-relay
  labels:
    app.kubernetes.io/name: acs-smtp-relay
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: acs-smtp-relay
  template:
    metadata:
      labels:
        app.kubernetes.io/name: acs-smtp-relay
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 65534
        runAsGroup: 65534
        fsGroup: 65534
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: relay
          image: <YOUR_CONTAINER_IMAGE_PATH>
          imagePullPolicy: Always
          ports:
            - name: smtp
              containerPort: 1025
            - name: health
              containerPort: 9090
          livenessProbe:
            httpGet:
              path: /
              port: health
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /
              port: health
            initialDelaySeconds: 5
            periodSeconds: 10
          env:
            - name: RUST_LOG
              value: "info"
            - name: ACS_SENDER_ADDRESS
              value: "<YOUR_SENDER_ADDRESS>"
            - name: ACS_CONNECTION_STRING
              valueFrom:
                secretKeyRef:
                  name: acs-relay-secrets
                  key: ACS_CONNECTION_STRING
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 128Mi
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: true
          volumeMounts:
            - name: tmp
              mountPath: /tmp
      volumes:
        - name: tmp
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: acs-smtp-relay-svc
  labels:
    app.kubernetes.io/name: acs-smtp-relay
spec:
  selector:
    app.kubernetes.io/name: acs-smtp-relay
  ports:
    - name: smtp
      protocol: TCP
      port: 25
      targetPort: 1025
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: acs-smtp-relay-pdb
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: acs-smtp-relay
